version: "3.7"

services:
  fastapi-app:
    build:
      context: ./fastapi-app # Dockerfile이 위치한 디렉토리 경로
      dockerfile: Dockerfile # Dockerfile 이름
    container_name: FastApi-app
    ports:
      - "5001:8000" # 호스트 5001 -> 컨테이너 8000 연결
    volumes:
      - ./fastapi-app:/app # 실시간 코드 반영을 위한 볼륨 마운트 (개발용)
      - /app/__pycache__ # 캐시 충돌 방지
    env_file:
      - ./fastapi-app/.env.example # 필요한 환경 변수 설정 (실제 .env가 있으면 그것을 사용하세요)
    restart: always
