# 프로젝트 기본 설정
sonar.projectKey=fastapi_app
sonar.projectName=FastAPI App
sonar.projectVersion=1.0

# 소스 코드 경로 (현재 디렉토리 기준 상대 경로)
sonar.sources=.

# SonarQube 서버 URL (docker-compose로 실행 중인 SonarQube의 주소)
sonar.host.url=http://localhost:9000

# 커버리지 경로 (pytest로 생성한 커버리지 결과를 SonarQube에 전달)
sonar.python.coverage.reportPaths=coverage.xml

# html 내부의 js 코드도 분석에서 제외
sonar.exclusions=**/*.js,**/*.css,**/*.html
